apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: fable:0.1
          imagePullPolicy: Never
          name: client
          ports:
            - containerPort: 8080
              
              
  vault policy write client - <<EOF
  path "secret/data/client/config" {
  capabilities = ["read"]
}
  EOF
Success! Uploaded policy: client
